DROP TABLE IF EXISTS crashes;
--SPLIT
CREATE TABLE IF NOT EXISTS crashes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    advisorySpeed INTEGER,
    bicycle INTEGER,
    bridge INTEGER,
    bus INTEGER,
    carStationWagon INTEGER,
    cliffBank INTEGER,
    location1 TEXT,
    location2 TEXT,
    severity TEXT,
    year INTEGER,
    ditch INTEGER,
    fatalCount INTEGER,
    fence INTEGER,
    flatHill TEXT,
    guardRail INTEGER,
    holiday TEXT,
    houseOrBuilding INTEGER,
    intersection TEXT,
    kerb INTEGER,
    light TEXT,
    minorInjuryCount INTEGER,
    moped INTEGER,
    motorcycle INTEGER,
    numberOfLanes INTEGER,
    objectThrownOrDropped INTEGER,
    otherObject INTEGER,
    otherVehicleType INTEGER,
    overBank INTEGER,
    parkedVehicle INTEGER,
    phoneBoxEtc INTEGER,
    pedestrian INTEGER,
    postOrPole INTEGER,
    roadCharacter TEXT,
    roadLane TEXT,
    roadSurface TEXT,
    roadworks INTEGER,
    schoolBus INTEGER,
    seriousInjuryCount INTEGER,
    slipOrFlood INTEGER,
    speedLimit INTEGER,
    strayAnimal INTEGER,
    streetLight TEXT,
    suv INTEGER,
    taxi INTEGER,
    tlaName TEXT,
    temporarySpeedLimit INTEGER,
    trafficControl TEXT,
    trafficIsland INTEGER,
    trafficSign INTEGER,
    train INTEGER,
    tree INTEGER,
    truck INTEGER,
    unknownVehicleType INTEGER,
    urban TEXT,
    vanOrUtility INTEGER,
    vehicle INTEGER,
    waterRiver INTEGER,
    weatherA TEXT,
    weatherB TEXT,
    lat REAL,
    lng REAL,
    UNIQUE (lat, lng));
--SPLIT
CREATE INDEX IF NOT EXISTS crashes_spatial_index ON crashes(lat, lng);